name: "schmiddim-action-gh-release-info"
author: Michael Schmitt
description: This action fetches informations about Github Releases (download asset url, tag name)
inputs:
  url:
    description: "url that must point to a Github Repo"
    required: true
  download_url_pattern:
    description: "Python Re pattern to look for"
    required: false
outputs:
  release_url:
    description: "Asset Url"
  release_tag:
    description: "Release Tag"
branding:
  color: red
  icon: download
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - --url=${{ inputs.url }}
    - --pattern=${{ inputs.download_url_pattern }}
