name: Integration Tests for the Action
on:
  push:
  workflow_dispatch:
jobs:
  release-info:
    runs-on: ubuntu-latest
    name: Integration Test
    steps:
      - name: Get Asset Url for an linux release
        uses: schmiddim/action-gh-release-info@master
        id: hello
        with:
          url: https://github.com/hpool-dev/chia-miner/
          download_url_pattern: .*linux
      - name: Download and extract
        uses: schmiddim/action-wget-unzip@v1
        with:
          url: ${{ steps.hello.outputs.release_url }}
          destination: i-do-not-care
      - name: output release tag
        run: echo ${{ steps.hello.outputs.release_tag }}
