name: Integration Tests for the Action
on:
  push:
  workflow_dispatch:
jobs:
  release-info:
    runs-on: ubuntu-latest
    name: Integration Test
    steps:
      - name: Get Asset Url for an linux release
        uses: schmiddim/action-gh-release-info@master
        id: fetch
        with:
          url: https://github.com/hpool-dev/chia-miner/
          mode: asset_url
          download_url_pattern: .*linux
      - name: Download and extract
        uses: schmiddim/action-wget-unzip@v2
        with:
          url: ${{ steps.fetch.outputs.release_info }}
          destination: i-do-not-care
